version: '3.9'

services:
  db_auth:
    image: postgres:14.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgadmin
      POSTGRES_DB: db_auth
    volumes:
      - authVol:/var/lib/postgresql/data
    networks:
      - authNet

volumes:
  authVol:

networks:
  authNet:
